version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DATABASE}
      - REDIS_URL=redis://${REDIS_HOST}:${REDIS_PORT}/0
    depends_on:
      - db
      - redis
      - antifraud
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

  redis:
    image: redis:latest
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

  antifraud:
    image: lodthe/prod-backend-antifraud:latest
    environment:
      - SERVER_PORT=9090
      - CACHE_DURATION_MS=5000
    ports:
      - "9090:9090"
    deploy:
      resources:
        reservations:
          cpus: '0.1'
          memory: 512M
    platform: linux/amd64


volumes:
  postgres_data:
